### ISSUE TITLE
Typo in configuration unset

### ISSUE THREAD

**Issue by halostatue** [cquintana92/git-switch-user#1]
https://github.com/cquintana92/git-switch-user/blob/e77b319b9965d008f9faf664f8737d882245f9ff/src/main.rs#L151

This produces a command line `git config unset --local commit.gpgsign`, but it should be `git config --unset --local commit.gpgsign`.

**Comment by cquintana92** [comment]
You are right, nice catch!

Fixed in: https://github.com/cquintana92/git-switch-user/commit/e5ca0f768b87c651e14c15d4ddbeb9696f293280

You can grab the latest release at: https://github.com/cquintana92/git-switch-user/releases/latest
